version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ${MNT_PATH}/data:/data:ro
    ports:
      - "5823:80"
    depends_on:
      - "ui"
      - "api"
    environment:
      SCRAPE_HOST: ${SCRAPE_HOST}
  ui:
    image: node:16.13.1
    working_dir: /app
    command: >
      sh -c "yarn install &&
             yarn start-port80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./crgw-ui:/app
  api:
    image: python:3.10-slim-bullseye
    working_dir: /app
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: >
      bash -c "python -m venv docker-venv &&
               source docker-venv/bin/activate &&
               pip install -r requirements.txt &&
               pip freeze > docker-pip-freeze.txt &&
               python main.py"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./crgw-api:/app
      - ${MNT_PATH}:/data:ro
    environment:
      CRG_REMOTE_HOST: ${CRG_REMOTE_HOST}
      CRG_REMOTE_APIKEY: ${CRG_REMOTE_APIKEY}
  daemon:
    container_name: daemon
    build:
      context: ./crgw-daemon
      dockerfile: Dockerfile
    command: python -m daemon
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MNT_PATH}:/mnt
