version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ${DATA_MNT_DIR}/data:/data:ro
    user: 0:0
    ports:
      - "5823:80"
    depends_on:
      - "ui"
      - "api"
    environment:
      TZ: ${TIMEZONE}
  ui:
    build:
      context: ./crgw-ui
      dockerfile: Dockerfile
    working_dir: /app
    command: nginx -g 'daemon off;'
    environment:
      TZ: ${TIMEZONE}
  api:
    image: python:3.11-slim-bullseye
    working_dir: /app
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: > # The use of venv helps with the container init times, but can cause occasional caching issues; purge the folder as needed.
      bash -c "python -m venv docker-venv &&
               source docker-venv/bin/activate &&
               pip install -r requirements.txt &&
               pip freeze > docker-pip-freeze.txt &&
               python main.py"
    volumes:
      - ./crgw-api:/app
      - ${DATA_MNT_DIR}/data:/data
      - ${LOG_DIR}:/var/log/crgw-api
    environment:
      TZ: ${TIMEZONE}
      CRG_REMOTE_HOST: ${CRG_REMOTE_HOST}
      CRG_REMOTE_APIKEY: ${CRG_REMOTE_APIKEY}
      YOUTUBE_APIKEY: ${YOUTUBE_APIKEY}
  daemon:
    container_name: daemon
    build:
      context: ./crgw-daemon
      dockerfile: Dockerfile
    command: python -m daemon
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      CRG_REMOTE_HOST: ${CRG_REMOTE_HOST}
      CRG_REMOTE_APIKEY: ${CRG_REMOTE_APIKEY}
    volumes:
      - ${CONFIG_PATH}:/config/config.yml:ro
      - ${DATA_MNT_DIR}:/mnt
      - ${LOG_DIR}:/var/log/crgw-daemon
